### ISSUE TITLE
Unable to start 2.x.x 

### ISSUE THREAD

**Issue by kasparmir** [seaky/nspanel_pro_tools_apk#104]
Hello I've been using the 1.1 version of app since its release. And it works like a charm.

Recently i tried to upgrade to 2.x.x versions of app. All of them including the latest one are crashing on my device. I tried uninstalling the old version before upgrade, cleaning apps's storage, reboot the device, different 2.x versions. I even tried upgrade of firmware (using your other app) to 2.3 and even to the 3.0 version. So now, I am running the 3.0 fw. But the outcome is always the same:

![image](https://github.com/seaky/nspanel_pro_tools_apk/assets/53423075/146816b4-1afa-4e86-9192-96592fc597bc)

When I downgrade back to the 1.1 it works like before. Can you please take a look at my issue? If there is something I can provide for diagnostics (some kind of logs, configuration details, etc) just tell me the exact adb command and I'll send it to you.

**Comment by seaky** [comment]
Could you please provide adb log here?
```
adb shell "ps -A | grep com.seaky.nspanelpro"
```
the second value of the result is the pid
```
adb logcat -d --pid=<pid>
```

**Comment by seaky** [comment]
Is this Sonoff?

**Comment by kasparmir** [comment]
Yes, it's Sonnoff NS Panel Pro bought last year in July. Formely shipped with 1.4.0 (if I remember correctly). I configured it using blackadder's tutorial. But I think, it's not important for my issue. I tried to get the logs twice (two attempts with two different PIDs) to be sure if they are the same. In both cases I've got following:
```
--------- beginning of main
06-22 17:54:48.782 15134 15134 I c       : Log level is RELEASE
06-22 17:54:48.805 15134 15134 D AndroidRuntime: Shutting down VM
--------- beginning of crash
06-22 17:54:48.806 15134 15134 E AndroidRuntime: FATAL EXCEPTION: main
06-22 17:54:48.806 15134 15134 E AndroidRuntime: Process: com.seaky.nspanelpro.tools, PID: 15134
06-22 17:54:48.806 15134 15134 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.seaky.nspanelpro.tools/com.seaky.nspanelpro.tools.ui.LaunchApp}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-22 17:54:48.806 15134 15134 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at com.seaky.nspanelpro.tools.ui.LaunchApp.onCreate(Unknown Source:43)
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7036)
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7027)
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
06-22 17:54:48.806 15134 15134 E AndroidRuntime:        ... 9 more
```

**Comment by seaky** [comment]
Ok i found a possible but I’m wondering about why it is not working for you but why for me or others.
What kind of launcher do you use?

**Comment by kasparmir** [comment]
I have the Lawnchair (version 1.2.1.2001) and Wallpanel app installed. None of them is set as default. But Wallpanel app is configured to run on boot. In the picture above in this issue I'm trying to launch Tool app from Lawnchair. Do you think that it could colide somehow?

**Comment by seaky** [comment]
will be fixed in v2.2.1

**Comment by seaky** [comment]
Some detail about the fix: the Lawnchair launches apps differently than ultrasmall launcher and I also found a typo in an if-then case so it is definitely a bug

**Comment by kasparmir** [comment]
As workaround I switched to the ultrasmall launcher. and it works. Thank you very much.

**Comment by seaky** [comment]
new version is available
