### ISSUE TITLE
crash when changing MQTT configuration

### ISSUE THREAD

**Issue by fcrozat** [seaky/nspanel_pro_tools_apk#82]
When changing MQTT setting, the application often crashes:

```
03-22 07:18:50.336  1367  1367 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-22 07:18:50.337  1367  1367 E AndroidRuntime: FATAL EXCEPTION: main
03-22 07:18:50.337  1367  1367 E AndroidRuntime: Process: com.seaky.nspanelpro.tools, PID: 1367
03-22 07:18:50.337  1367  1367 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean a1.f.d()' on a null object reference
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at m0.c.j(Unknown Source:7)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at j0.a.deactivate(Unknown Source:5)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at m0.c.onSharedPreferenceChanged(Unknown Source:27)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:561)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:444)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at android.support.v7.preference.TwoStatePreference.D(Unknown Source:65)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at android.support.v7.preference.TwoStatePreference.n(Unknown Source:14)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at android.support.v7.preference.Preference.u(Unknown Source:7)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at android.support.v7.preference.SwitchPreferenceCompat.u(Unknown Source:0)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at android.support.v7.preference.Preference$a.onClick(Unknown Source:2)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at android.view.View.performClick(View.java:6294)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:24770)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:790)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-22 07:18:50.337  1367  1367 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by seaky** [comment]
Hi,

Most probably you didn't fill out the host or userName fields. Both must be filled out. 
In the log you should find a "Unable to connect mqtt may [host,userName] is null"

But indeed the crash is a bug, which is caused by the inproper error handling. I'll fix it in v2.1.1
